language: python
python:
  - "2.7"

cache: pip
services:
  - mongodb

# install dependencies
install: 
  - pip install -r requirements.txt

# run tests
script:
  - coverage run --source unittest tests.py

after_success:
  - coveralls