language: python
python:
  - "2.7"

cache: pip
services:
  - mongodb

# install dependencies
install: 
  - pip install -r requirements.txt

# run tests
script:
  - coverage run --omit=app/templates --source=app/ -m unittest tests

after_success:
  - coveralls